(()=>{
const SOURCE_AREAS=['Ciencias Sociales','Ciencias Naturales','Tecnologías'];
const FORMAT_TYPES=['Seminario','Proyecto','Módulo','Espacio integrado','Ateneo','Clínica','Observatorio','Trayecto','Otro'];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function state(){try{return window.app||window.eval('app')}catch{return null}}
function data(){try{return window.DATA||window.eval('DATA')}catch{return[]}}
function current(){return state()?.current||null}
function persist(){const s=state();if(s)localStorage.setItem('pciAppV2',JSON.stringify(s))}
function ensure(){const s=state();if(!s)return null;if(!Array.isArray(s.otherFormats))s.otherFormats=[];Object.values(s.areas||{}).forEach(a=>(a.groups||[]).forEach(g=>{if(g.term==null)g.term='';if(g.format==null)g.format=''}));persist();return s}
function termOptions(v){return '<option value="">Seleccionar</option>'+Array.from({length:10},(_,i)=>i+1).map(n=>`<option value="${n}" ${String(v)===String(n)?'selected':''}>Cuatrimestre ${n}</option>`).join('')}
function coverage(area){const s=ensure(),all=data().filter(x=>x.area===area),used=new Set();(s.areas?.[area]?.groups||[]).forEach(g=>(g.items||[]).forEach(id=>used.add(id)));(s.otherFormats||[]).filter(f=>f.sourceArea===area).forEach(f=>(f.items||[]).forEach(id=>used.add(id)));return{total:all.length,covered:all.filter(x=>used.has(x.id)).length,pending:all.filter(x=>!used.has(x.id))}}
function addGlobalCoverage(){const grid=$('areaGrid');if(!grid||$('crossCoverage'))return;const box=document.createElement('section');box.id='crossCoverage';box.className='card';box.style.marginBottom='14px';grid.parentNode.insertBefore(box,grid);renderGlobalCoverage()}
function renderGlobalCoverage(){const box=$('crossCoverage');if(!box)return;const rows=SOURCE_AREAS.map(a=>({a,...coverage(a)})),T=rows.reduce((n,r)=>n+r.total,0),C=rows.reduce((n,r)=>n+r.covered,0);box.innerHTML=`<h2 style="margin-top:0">Cobertura total priorizada</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px">${rows.map(r=>`<div style="padding:12px;border:1px solid #dbe5e8;border-radius:14px"><b>${esc(r.a)}</b><div style="font-size:1.4rem;font-weight:900">${r.covered}/${r.total}</div><div class="muted">${r.total?Math.round(r.covered/r.total*100):0}% cubierto · ${r.total-r.covered} pendientes</div></div>`).join('')}</div><p style="margin-bottom:0"><b>Total general:</b> ${C}/${T} contenidos cubiertos (${T?Math.round(C/T*100):0}%).</p>`}
function addFormatsCard(){const grid=$('areaGrid');if(!grid||$('otherFormatsCard'))return;const b=document.createElement('button');b.id='otherFormatsCard';b.className='area card';b.innerHTML='<strong>Otros formatos curriculares</strong><div class="area-meta">Cobertura horaria y curricular complementaria</div><div class="status warn">Seminarios, proyectos, módulos y otros formatos</div>';b.onclick=openFormats;grid.appendChild(b)}
function addMapButton(){const actions=document.querySelector('.top .actions');if(!actions||$('pciMapButton'))return;const b=document.createElement('button');b.id='pciMapButton';b.className='btn primary';b.textContent='Mapa completo';b.onclick=()=>{persist();window.open('trayectoria-pci.html?v=movible-2','_blank')};actions.insertBefore(b,actions.lastElementChild||null)}
function enhanceTerms(){const a=current(),s=ensure();if(!a||!['Artes','Tecnologías'].includes(a)||!s.areas?.[a])return;document.querySelectorAll('#groups .group').forEach((card,i)=>{const g=s.areas[a].groups[i],editor=card.querySelector('.editor');if(!g||!editor||editor.querySelector('.enh-term'))return;const wrap=document.createElement('div');wrap.className='enh-term';wrap.innerHTML=`<label class="label">Cuatrimestre de implementación *</label><select>${termOptions(g.term)}</select>`;editor.appendChild(wrap);wrap.querySelector('select').onchange=e=>{g.term=e.target.value;persist();renderGlobalCoverage()}})}
function openFormats(){ensure();let modal=$('formatsModal');if(!modal){modal=document.createElement('div');modal.id='formatsModal';modal.innerHTML=`<style>#formatsModal{position:fixed;inset:0;z-index:200;background:#102b3ab8;display:grid;place-items:center;padding:12px}.fm{width:min(1180px,100%);max-height:94vh;overflow:auto;background:#f4f7f8;border-radius:22px;padding:16px}.fm-head{display:flex;align-items:center;gap:10px;flex-wrap:wrap;position:sticky;top:-16px;background:#f4f7f8;padding:12px 0;z-index:2}.fm-head h2{margin:0 auto 0 0}.fm-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:12px}.fm-card{background:#fff;border:1px solid #dbe5e8;border-radius:16px;padding:13px}.fm-card input,.fm-card select,.fm-card textarea{width:100%;padding:9px;border:1px solid #dbe5e8;border-radius:10px;margin:4px 0 8px}.fm-card textarea{min-height:76px}.fm-content{max-height:240px;overflow:auto;border:1px solid #dbe5e8;border-radius:10px;padding:8px}.fm-item{display:grid;grid-template-columns:24px 1fr;gap:6px;font-size:.78rem;padding:5px;border-bottom:1px solid #edf1f2}.fm-actions{display:flex;gap:8px;justify-content:flex-end}.fm-cov{background:#eaf9f7;border:1px solid #c9ebe6;border-radius:13px;padding:10px;margin-bottom:12px}@media(max-width:700px){.fm-grid{grid-template-columns:1fr}.fm{padding:10px}}</style><div class="fm"><div class="fm-head"><h2>Otros formatos curriculares</h2><button id="fmAdd" class="btn mint">+ Agregar formato</button><button id="fmClose" class="btn">Cerrar</button></div><div id="fmCoverage" class="fm-cov"></div><div id="fmGrid" class="fm-grid"></div></div>`;document.body.appendChild(modal);$('fmClose').onclick=()=>modal.remove();$('fmAdd').onclick=()=>{const s=ensure();s.otherFormats.push({id:'of-'+Date.now(),name:'Nuevo formato curricular',formatType:'Proyecto',hours:'',term:'',character:'Obligatorio',sourceArea:'Ciencias Sociales',objective:'',context:'',items:[],order:s.otherFormats.length});persist();renderFormats()}}renderFormats()}
function renderFormats(){const s=ensure(),grid=$('fmGrid');if(!grid)return;const cov=SOURCE_AREAS.map(a=>({a,...coverage(a)}));$('fmCoverage').innerHTML=cov.map(r=>`<b>${esc(r.a)}:</b> ${r.covered}/${r.total} (${r.total?Math.round(r.covered/r.total*100):0}%)`).join(' · ');
grid.innerHTML=(s.otherFormats||[]).map((f,i)=>{const rows=data().filter(x=>x.area===f.sourceArea);return `<article class="fm-card" data-i="${i}"><label>Nombre</label><input data-k="name" value="${esc(f.name)}"><label>Tipo de formato</label><select data-k="formatType">${FORMAT_TYPES.map(x=>`<option ${f.formatType===x?'selected':''}>${x}</option>`).join('')}</select><label>Horas cátedra</label><input data-k="hours" type="number" min="0" value="${esc(f.hours)}"><label>Cuatrimestre</label><select data-k="term">${termOptions(f.term)}</select><label>Carácter</label><select data-k="character"><option ${f.character==='Obligatorio'?'selected':''}>Obligatorio</option><option ${f.character==='Electivo'?'selected':''}>Electivo</option></select><label>Área de contenidos</label><select data-k="sourceArea">${SOURCE_AREAS.map(a=>`<option ${f.sourceArea===a?'selected':''}>${a}</option>`).join('')}</select><label>Objetivos</label><textarea data-k="objective">${esc(f.objective)}</textarea><label>Contexto / descripción</label><textarea data-k="context">${esc(f.context)}</textarea><label>Contenidos priorizados (${(f.items||[]).length})</label><input class="fm-search" placeholder="Buscar contenido"><div class="fm-content">${rows.map(x=>`<label class="fm-item" data-text="${esc((x.subject+' '+x.axis+' '+x.text).toLowerCase())}"><input type="checkbox" data-content="${x.id}" ${(f.items||[]).includes(x.id)?'checked':''}><span><b>${esc(x.subject)}</b> · ${esc(x.axis||'Sin eje')}<br>${esc(x.text)}</span></label>`).join('')}</div><div class="fm-actions"><button class="btn danger" data-del="${i}">Eliminar</button></div></article>`}).join('')||'<div class="empty">Todavía no hay formatos curriculares. Tocá “Agregar formato”.</div>';
document.querySelectorAll('.fm-card').forEach(card=>{const i=+card.dataset.i,f=s.otherFormats[i];card.querySelectorAll('[data-k]').forEach(el=>el.onchange=el.oninput=()=>{f[el.dataset.k]=el.value;persist();if(el.dataset.k==='sourceArea')renderFormats();else renderGlobalCoverage()});card.querySelectorAll('[data-content]').forEach(ch=>ch.onchange=()=>{const id=ch.dataset.content;if(ch.checked&&!f.items.includes(id))f.items.push(id);if(!ch.checked)f.items=f.items.filter(x=>x!==id);persist();renderFormats();renderGlobalCoverage()});const search=card.querySelector('.fm-search');search.oninput=()=>{const q=search.value.toLowerCase();card.querySelectorAll('.fm-item').forEach(x=>x.style.display=x.dataset.text.includes(q)?'grid':'none')};card.querySelector('[data-del]').onclick=()=>{if(confirm('¿Eliminar este formato curricular?')){s.otherFormats.splice(i,1);persist();renderFormats();renderGlobalCoverage()}}})}
function tick(){addMapButton();if($('areaGrid')){addGlobalCoverage();addFormatsCard();renderGlobalCoverage()}enhanceTerms()}
const obs=new MutationObserver(tick);obs.observe(document.documentElement,{subtree:true,childList:true});ensure();setInterval(tick,900);tick();
})();